
namespace System.Networking.Protocols.Bootstrap
{
    /// <summary>
    /// 
    /// </summary>
    public enum BootstrapConfigurationSetting : byte
    {
        None = 0x00,
        AllSubnetsAreLocal = 0x1b,
        ARPCacheTimeout = 0x23,
        BootFileName = 0x43,
        BootFileSize = 13,
        BroadcastAddress = 0x1c,
        ClientIdentifier = 0x3d,
        CookieServer = 8,
        DefaultFingerServer = 0x49,
        DefaultIPTimeToLive = 0x17,
        DefaultIRCServer = 0x4a,
        DefaultWWWServer = 0x48,
        DhcpMessageType = 0x35,
        DomainName = 15,
        DomainNameServer = 6,
        EthernetEncapsulation = 0x24,
        ExtensionsPath = 0x12,
        HostName = 12,
        ImpressServer = 10,
        InterfaceMTU = 0x1a,
        IPAddressBootstrapConfigurationTime = 0x33,
        IpForwarding = 0x13,
        LogServer = 7,
        LPRServer = 9,
        MaskSupplier = 30,
        MaximumDatagramReAssemblySize = 0x16,
        MaximumDHCPMessageSize = 0x39,
        MeritDump = 14,
        Message = 0x38,
        MobileIPHomeAgent = 0x44,
        NameServer = 5,
        NetBIOSoverTCPIPDatagramDistributionServer = 0x2d,
        NetBIOSoverTCPIPNameServer = 0x2c,
        NetBIOSoverTCPIPNodeType = 0x2e,
        NetBIOSoverTCPIPScope = 0x2f,
        NetworkInformationServers = 0x29,
        NetworkInformationServiceDomain = 40,
        NetworkInformationServicePlusDomain = 0x40,
        NetworkInformationServicePlusServers = 0x41,
        NetworkTimeProtocolServers = 0x2a,
        NNTPServer = 0x47,
        NonLocalSourceRouting = 20,
        OptionOverload = 0x34,
        ParameterRequestList = 0x37,
        PathMTUAgingTimeout = 0x18,
        PathMTUPlateauTable = 0x19,
        PerformMaskDiscovery = 0x1d,
        PerformRouterDiscovery = 0x1f,
        PolicyFilter = 0x15,
        POP3Server = 70,
        RebindingTimeValue_T2 = 0x3b,
        RenewalTimeValue_T1 = 0x3a,
        RequestedIPAddress = 50,
        ResourceLocServer = 11,
        RootPath = 0x11,
        Router = 3,
        RouterSolicitationAddress = 0x20,
        ServerIdentifier = 0x36,
        SMTPServer = 0x45,
        StaticRoute = 0x21,
        STDAServer = 0x4c,
        StreetTalkServer = 0x4b,
        SubnetMask = 1,
        SwapServer = 0x10,
        TCPDefaultTTL = 0x25,
        TCPKeepaliveGarbage = 0x27,
        TCPKeepaliveInterval = 0x26,
        TFTPServerName = 0x42,
        TimeOffset = 2,
        TimeServer = 4,
        TrailerEncapsulation = 0x22,
        Vendorclassidentifier = 60,
        VendorSpecificInformation = 0x2b,
        XWindowSystemDisplayManager = 0x31,
        XWindowSystemFontServer = 0x30
    };
};